"""empty message

Revision ID: 3b5298788134
Revises: f67c0d54fb5f
Create Date: 2024-08-12 20:59:53.618243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5298788134'
down_revision = 'f67c0d54fb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('body', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('comments_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_comments_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_comments_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_comments_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_comments_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('likes_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('likes_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_likes_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_likes_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_likes_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_likes_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('posts_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('posts_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_posts_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_posts_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_posts_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_posts_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('token_block_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('token_block_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_token_block_list_jti'), ['jti'], unique=False)

    op.create_table('token_block_list_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.String(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('token_block_list_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_token_block_list_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='public'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_users_id'), ['id'], unique=False)

    op.create_table('users_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('users_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_users_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_users_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_users_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_users_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_posts_id'), ['id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['public.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_comments_id'), ['id'], unique=False)

    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['public.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_likes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_likes_id'))

    op.drop_table('likes', schema='public')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_comments_id'))

    op.drop_table('comments', schema='public')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_posts_id'))

    op.drop_table('posts', schema='public')
    with op.batch_alter_table('users_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_users_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_users_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_users_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_users_version_end_transaction_id'))

    op.drop_table('users_version', schema='public')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_users_id'))

    op.drop_table('users', schema='public')
    with op.batch_alter_table('token_block_list_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_jti'))
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_version_end_transaction_id'))

    op.drop_table('token_block_list_version', schema='public')
    with op.batch_alter_table('token_block_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_token_block_list_jti'))

    op.drop_table('token_block_list', schema='public')
    with op.batch_alter_table('posts_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_posts_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_posts_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_posts_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_posts_version_end_transaction_id'))

    op.drop_table('posts_version', schema='public')
    with op.batch_alter_table('likes_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_likes_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_likes_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_likes_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_likes_version_end_transaction_id'))

    op.drop_table('likes_version', schema='public')
    with op.batch_alter_table('comments_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_comments_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_comments_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_comments_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_comments_version_end_transaction_id'))

    op.drop_table('comments_version', schema='public')
    # ### end Alembic commands ###
