"""empty message

Revision ID: f67c0d54fb5f
Revises: f28047d603ba
Create Date: 2024-08-12 19:18:59.064768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67c0d54fb5f'
down_revision = 'f28047d603ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('likes_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_likes_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_likes_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_likes_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_likes_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('posts_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('body', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='public'
    )
    with op.batch_alter_table('posts_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_posts_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_posts_version_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_posts_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_posts_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('likes_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_author_id_fkey', 'users', ['author_id'], ['id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('likes_post_id_fkey', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('likes_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_author_id_fkey', 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key('comments_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('posts_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_posts_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_posts_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_posts_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_posts_version_end_transaction_id'))

    op.drop_table('posts_version', schema='public')
    with op.batch_alter_table('likes_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_likes_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_public_likes_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_public_likes_version_id'))
        batch_op.drop_index(batch_op.f('ix_public_likes_version_end_transaction_id'))

    op.drop_table('likes_version', schema='public')
    # ### end Alembic commands ###
